default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: vuongkykhan
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ecommerce_development

test:
  <<: *default
  database: ecommerce_test

production:
  <<: *default
  database: ecommerce_production
  username: vuongkykhan
  password: 123456
